name: better_lints_example
description: Example for Better Lints
private: true
version: 1.0.0
homepage: https://github.com/adhunitech/better_lints
repository: https://github.com/adhunitech/better_lints

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  better_lints: ^1.0.0