name: better_lints
description: A curated set of lint rules for Dart and Flutter projects to ensure consistency, maintainability, and best practices.
version: 1.0.4
homepage: https://github.com/adhunitech/better_lints
repository: https://github.com/adhunitech/better_lints
topics: 
  - lints
  - dart
  - flutter

environment:
  sdk: '>=3.7.0 <4.0.0'

dev_dependencies:
  html: ^0.15.0
  http: ^1.0.0
  yaml: ^3.1.0
