name: better_lints
description: A curated set of lint rules for Dart and Flutter projects to ensure consistency, maintainability, and best practices.
version: 5.0.0
homepage: https://github.com/adhunitech/better_lints
repository: https://github.com/adhunitech/better_lints
topics: 
  - lints
  - dart
  - flutter

environment:
  sdk: ^3.8.1
