name: Better Lints Build

on:
  push:
    paths: [ /**, .github/workflows/build.yaml ]
    
  pull_request:
    paths: [ /**, .github/workflows/build.yaml ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2.18.0
    - run: dart pub get
    - run: dart analyze
